siberiacancode/reactuse

src/hooks/useWindowEvent/useWindowEvent.ts
https://github.com/siberiacancode/reactuse/issues/28
=> feat(docs): useWindowEvent

src/hooks/useDocumentVisibility/useDocumentVisibility.demo.tsx, src/hooks/useDocumentVisibility/useDocumentVisibility.ts
Добавил jsdoc и демо для useDocumentVisibility
=> feat(docs&demo): useDocumentVisibility

src/hooks/useNonInitialEffect/useNonInitialEffect.demo.tsx, src/hooks/useNonInitialEffect/useNonInitialEffect.ts
Сделал jsdoc и демо для useNonInitialEffect
=> feat(docs&demo):useNonInitialEffect

src/hooks/useStep/useStep.ts
=> [Feat]: useStep Hook

src/hooks/useStep/useStep.demo.tsx, src/hooks/useStep/useStep.test.ts, src/hooks/useStep/useStep.ts
#59 #58 #57 
Fix a bug, if user want set custom initial step (ex. max step is 2, initial is 0):
```typescript
const step = useStep({ initial: 0, max: 2 });
console.log(step.isFirst); // false
step.next(); // currentStep is 1
console.log(step.isFirst); // true 
```
=> [Feat]: useStep hook jsdoc, demo and tests

src/hooks/useDefault/useDefault.test.ts
=> [test]: useDefault hook tests

src/hooks/useDocumentVisibility/useDocumentVisibility.test.ts
Сделал тесты для useDocumentVisibility
=> [test]: useDocumentVisibility

src/hooks/useSet/useSet.test.ts
Add tests for useSet hook
This pr will close this task https://github.com/siberiacancode/reactuse/issues/76
=> [test]: add tests for useSet hook

src/hooks/useClickOutside/useClickOutside.ts
Add jsdoc for useClickOutside hook
This pr will close this task #23
=> [doc]: add jsdoc for useClickOutside hook🤓

src/hooks/useFavicon/useFavicon.test.ts
=> [test]: useFavicon hook tests

src/hooks/useIsFirstRender/useIsFirstRender.test.ts
сделал тесты для useIsFirstRender #107
=> [test]: useIsFirstRender

src/hooks/useCopyToClipboard/useCopyToClipboard.test.ts
Added missing tests for useCopyToClipboard hook. This PR will close #33.
=> test: add tests for useCopyToClipboard

src/hooks/useQueue/useQueue.test.ts
Сделал тесты для useQueue #101
=> [test]: useQueue

src/hooks/useToggle/useToggle.test.ts
Added missing tests for useToggle hook. This PR will close #96.
=> test: add missing tests for useToggle hook

src/hooks/useOnline/useOnline.test.ts
=> [test]: useOnline

src/hooks/usePageLeave/usePageLeave.test.ts
=> [test]: usePageLeave

src/hooks/useHash/useHash.demo.tsx
=> [bug]: useHash

src/hooks/useClickOutside/useClickOutside.test.ts
=> [test]: useClickOutside

src/hooks/useTimeout/useTimeout.test.ts
=> [test]: useTimeout

src/hooks/useWindowSize/useWindowSize.test.ts
=> [test]: useWindowSize

src/hooks/useOperatingSystem/useOperatingSystem.test.ts
=> test: add tests for useOperatingSystem

src/hooks/useBattery/useBattery.test.ts, src/hooks/useBattery/useBattery.ts
=> [test]: useBattery

src/hooks/useTime/useTime.test.ts
Добавил тесты для useTime https://github.com/siberiacancode/reactuse/issues/156
=> [test]: useTime tests

docs/src/components/meta.vue, src/hooks/useDefault/useDefault.ts, src/hooks/useDisclosure/useDisclosure.ts, src/hooks/useField/useField.ts, src/hooks/useList/useList.ts, src/hooks/useLogger/useLogger.ts, src/hooks/useMap/useMap.ts, src/hooks/useMutation/useMutation.ts, src/hooks/usePaint/usePaint.ts, src/hooks/useQuery/useQuery.ts, src/hooks/useQueue/useQueue.ts, src/hooks/useSet/useSet.ts, src/hooks/useStep/useStep.ts, src/hooks/useToggle/useToggle.ts, src/hooks/useWizard/useWizard.ts
Дописал все остальные хуки, не успел запушить, предыдущий PR слили за секунду до пуша
=> chore: finalized all hooks

src/hooks/useScript/useScript.test.ts
Добавил тесты для useScript #100
=> [test]: useScript

src/hooks/useOffsetPagination/useOffsetPagination.demo.tsx, src/hooks/useOffsetPagination/useOffsetPagination.ts
Добавил хук useOffsetPagination #196
=> [feat]: useOffsetPagination

src/hooks/useKeyPressEvent/useKeyPressEvent.demo.tsx, src/hooks/useKeyPressEvent/useKeyPressEvent.ts
jsdoc и демо для useKeyPressEvent #40
=> [doc]: useKeyPressEvent

src/hooks/index.ts, src/hooks/usePostMessage/usePostMessage.demo.tsx, src/hooks/usePostMessage/usePostMessage.ts
=> feat: add usePostMessage hook

src/hooks/useQuery/useQuery.test.ts, src/hooks/useQuery/useQuery.ts
- add unit tests for useQuery hook
- fix isLoading state when refresh request called
=> [useQuery] fixed refetching and added unit tests

src/hooks/useGeolocation/useGeolocation.test.ts, src/hooks/useGeolocation/useGeolocation.ts
=> test: add test for useGeolocation

src/hooks/useDocumentEvent/useDocumentEvent.test.ts
Добавил тесты для useDocumentEvent https://github.com/siberiacancode/reactuse/issues/174
=> [test]: useDocumentEvent tests

src/hooks/useHover/useHover.test.ts, src/hooks/useHover/useHover.ts
=> [test]: useHover

src/hooks/useMediaQuery/useMediaQuery.test.ts
#75 
https://github.com/vitest-dev/vitest/issues/821
=> [test]: Добавил тесты для хука useMediaQuery

packages/core/src/hooks/useDebounceValue/useDebounceValue.test.ts
=> Added tests for useDebounceValue

packages/core/src/helpers/createEventEmitter/createEventEmitter.test.ts
Issue #362 
Fixed import error in createEventEmitter.test.ts
=> Fixed import error that crushed precommit script

packages/core/src/hooks/useOffsetPagination/useOffsetPagination.test.ts
test cases for [issue](https://github.com/siberiacancode/reactuse/issues/380)
=> test/use-offset-pagination 🧊 chore: write test for hook

packages/core/src/hooks/useOrientation/useOrientation.test.tsx
Added test for useOrientation hook
=> #381 🧊 [test]: Test for useOrientation #381
